[providers]
node = "18.x"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x", "openssl", "pkg-config"]

[phases.install]
cmds = [
    "npm ci --prefix backend"
]

[phases.build] 
cmds = [
    "npx prisma generate --schema=backend/prisma/schema.prisma",
    "npm run build --prefix backend"
]

[start]
cmd = "npx prisma migrate deploy --schema=backend/prisma/schema.prisma && node backend/dist/server.js"