providers = ["node"]

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x", "openssl", "pkg-config"]

[phases.install]
cmds = [
    "cd backend && npm ci"
]

[phases.build]
cmds = [
    "cd backend && npm run build"
]

[start]
cmd = "cd backend && npm start"