[providers]
node = "18.x"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x", "openssl", "pkg-config"]

[phases.install]
cmds = [
    "npm ci --prefix backend"
]

[phases.build] 
cmds = [
    "cd backend && npx prisma generate",
    "cd backend && npm run build"
]

[start]
cmd = "cd backend && node dist/server.js"