[providers]
node = "18.x"

[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x", "openssl"]

[phases.install]
workDir = "/app/backend"
cmds = ["npm ci"]

[phases.build]
workDir = "/app/backend" 
cmds = [
    "npx prisma generate",
    "npm run build"
]

[start]
workDir = "/app/backend"
cmd = "npm start"