[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x', 'openssl']

[phases.install]
cmds = [
  'cd backend',
  'npm ci'
]

[phases.build]
cmds = [
  'cd backend',
  'npx prisma generate',
  'npm run build'
]

[start]
cmd = 'cd backend && npm start'

[variables]
NODE_ENV = 'production'
OPENSSL_CONF = '/dev/null'