# Root level nixpacks configuration to help Railway detect the project structure
[providers]
  node = "18"

[variables]
  NODE_ENV = "production"

# This will help Railway understand this is a monorepo
[phases.setup]
  nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
  cmd = "echo 'This is a monorepo. Please deploy backend and frontend separately.'"

[start]
  cmd = "echo 'Please deploy from backend/ or frontend/ directories'"