# 🎨 Render Blueprint - Golden Errands Platform
# Complete one-click deployment for backend + frontend + database

services:
  # Backend API Service
  - type: web
    name: golden-errands-api
    runtime: node
    region: oregon
    plan: free
    branch: main
    rootDir: backend
    buildCommand: bash build.sh
    startCommand: npm start
    healthCheckPath: /health
    numInstances: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_ACCESS_EXPIRY
        value: 15m
      - key: JWT_REFRESH_EXPIRY
        value: 7d
      - key: DATABASE_URL
        fromDatabase:
          name: golden-errands-db
          property: connectionString
      - key: CORS_ORIGIN
        value: "*"

  # Frontend Static Site
  - type: web
    name: golden-errands-frontend
    runtime: static
    region: oregon
    plan: free
    branch: main
    rootDir: frontend
    buildCommand: bash build.sh
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: golden-errands-api
          property: host

databases:
  # PostgreSQL Database
  - name: golden-errands-db
    databaseName: golden_errands
    user: golden_errands_user
    plan: free
    region: oregon
    ipAllowList: []
