# Render Blueprint for Golden Errands
# This file configures all services for one-click deployment

services:
  # Backend API Service
  - type: web
    name: golden-errands-api
    env: node
    region: oregon
    plan: free
    branch: main
    buildCommand: cd backend && npm install && npm run build && npx prisma generate
    startCommand: cd backend && node start-production.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_ACCESS_EXPIRY
        value: 15m
      - key: JWT_REFRESH_EXPIRY
        value: 7d
      - key: DATABASE_URL
        fromDatabase:
          name: golden-errands-db
          property: connectionString
      - key: CORS_ORIGIN
        sync: false

  # Frontend Static Site
  - type: web
    name: golden-errands-frontend
    env: static
    region: oregon
    plan: free
    branch: main
    buildCommand: cd frontend && npm install && npm run build:vite
    staticPublishPath: ./frontend/dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    envVars:
      - key: VITE_API_URL
        sync: false

databases:
  # PostgreSQL Database
  - name: golden-errands-db
    databaseName: golden_errands
    user: golden_errands_user
    plan: free
    region: oregon
